var GAME_LEVELS = [
   ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                 o              ",
   "                                                           o  xxxxxx            ",
   "                                                       -  xxx|     x            ",
   "                                                   o  xxx|         x            ",
   "                                               -  xxx|             x            ",
   "                                           o  xxx|                 x            ",
   "                                       -  xxx|                     x            ",
   "                                   o  xxx|                         x            ",
   "  xx                           -  xxx|                             x            ",
   "  x                        o  xxx|                                 x            ",
   "  x                    -  xxx|                                     x            ",
   "  x                o  xxx|                                         x            ",
   "  x  @           xxxx|                                             x            ",
   "  xxxxxxxxxxxxxx                                                   x            ",
   "               x                                                   x          o ",
   "               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!xxx",
   "               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                            x     xxxxx    -                                                  ",
   "                                            xx    x   x                                                       ",
   "                                            x     x   x    o                                                  ",
   "                                            x    xx   xxxxxxx                                                 ",
   "                                            x     x         x                                                 ",
   "                                            x     x     x   xxxxxxx                                           ",
   "                                            xx    x     xxxxx     x    -                                      ",
   "                                            x     x     x  x      x                                           ",
   "                                            x    xx     x  x      x    o                                      ",
   "                                            x     x        x      xxxxxx                                      ",
   "                                            x     x                    x                                      ",
   "                                            xx    x             xxxxxx x                                      ",
   "                                            x     x             x    x xxxxxxxx                               ",
   "                                            x    xx             x      x      x                               ",
   "                                            x     x             xxxxxxxx      x                               ",
   "                                            x     x             x  x   x      x                               ",
   "                                            xx    x             x  x   x      x                               ",
   "                                            x     x                x          xxxxxxxxxxxxxxxxxx              ",
   "                                            x    xx                x          x   x   x  x  x  x              ",
   "                                            x     x                           x   x   x  x  x  x              ",
   "                                            x     x                           v       x  x  x                 ",
   "                                            xx    x                                   x                       ",
   "                            xxxxxxx         x     x                                   v                       ",
   "                            x!!!!!!!!!!!    x    xx                                                           ",
   "                            xxxxxxxxxxxv    x     x                                                           ",
   "                             x              x     x                                                           ",
   "                             x              xx    x                                                           ",
   "                         xxxxx              x     x                                                           ",
   "  xxx                    x             xxxxxx    xx                                                        x  ",
   "  x x             xxxxxxxx             x          x                                                        x  ",
   "  x               x!!!x                x          x                                                        x  ",
   "  x               xxxxx                    xxxxxxxx                                                        x  ",
   "  x                 o                      x                                                               x  ",
   "  x                                   xxxxxx                                                               x  ",
   "  x                xxx            xxxxx                                  o                                 x  ",
   "  x               xxxxx           x                                     xxx                       xxx      x  ",
   "  x               oxxx-           x                                     x x          xx           x x      x  ",
   "  x                xxx        xxxxx                                    xx!xx       xx!!xx        xx!xx     x  ",
   "  x      @          x         x   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!xx!!!!xx!!!!!!xx!!!!!xx!!!xx!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                  xxxxx       ",
   "                                                                                                     ox       ",
   "                                                             xxxxxx|xxxxx|xxxxx|xxxxx|xxxxx|xxxxx|xxxxx       ",
   "                                                             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ",
   "                                                          xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ",
   "                                                             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ",
   "                                                  xxxxxx     xxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxxx       ",
   "                                                                                                              ",
   "                                                        xxxxxx                                                ",
   "                                                                xxxxxxxxxx                                    ",
   "                                                                             xxxx                             ",
   "                                                                                      xxx                     ",
   "                                                                                                              ",
   "                                                                                   xxx                        ",
   "                                                                                                              ",
   "                                                                                      xxx                     ",
   "                                                                                             xxx              ",
   "                                                                                         -                    ",
   "  !!!!!!!!!!!                                                                           xxx                   ",
   "  xxxxxxxxxxv                                                                                                 ",
   "                                                                                            xxxx              ",
   "                                                                                            x                 ",
   "     @                                                                                   xxxx                 ",
   "  xxxxxxx                                     xxxxx                      o               x                    ",
   "        x=     o         -          o        =x   x    xxx     xxx      xxx    xxx    xxxx                    ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;

